apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    # Label taxonomy — required by OPA require-namespace-labels policy
    team:       {{ .Values.team }}
    env:        {{ .Values.env }}
    model:      saas-pooled
    customer:   {{ .Values.customer }}
    managed-by: argocd
    # SaaS-specific labels
    saas.tier:  {{ .Values.customerTier }}
