# registry.k8s.io/pause:3.9 → ACCOUNT.dkr.ecr.REGION.amazonaws.com/k8s/pause:3.9
---
apiVersion: mutations.gatekeeper.sh/v1
kind: AssignImage
metadata:
  name: rewrite-k8s-registry-containers
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    scope: Namespaced
  location: "spec.containers[name:*].image"
  parameters:
    assignDomain: "REPLACE_WITH_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"
    assignPath: "k8s"
    pathTests:
      - subPath: "domain"
        condition: In
        value:
          - "registry.k8s.io"
---
apiVersion: mutations.gatekeeper.sh/v1
kind: AssignImage
metadata:
  name: rewrite-k8s-registry-init-containers
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    scope: Namespaced
  location: "spec.initContainers[name:*].image"
  parameters:
    assignDomain: "REPLACE_WITH_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"
    assignPath: "k8s"
    pathTests:
      - subPath: "domain"
        condition: In
        value:
          - "registry.k8s.io"
