# quay.io/prometheus/prometheus:v3.0 → ACCOUNT.dkr.ecr.REGION.amazonaws.com/quay/prometheus/prometheus:v3.0
---
apiVersion: mutations.gatekeeper.sh/v1
kind: AssignImage
metadata:
  name: rewrite-quay-io-containers
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    scope: Namespaced
  location: "spec.containers[name:*].image"
  parameters:
    assignDomain: "555555555555.dkr.ecr.us-east-1.amazonaws.com"
    assignPath: "quay"
    pathTests:
      - subPath: "domain"
        condition: In
        value:
          - "quay.io"
---
apiVersion: mutations.gatekeeper.sh/v1
kind: AssignImage
metadata:
  name: rewrite-quay-io-init-containers
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    scope: Namespaced
  location: "spec.initContainers[name:*].image"
  parameters:
    assignDomain: "555555555555.dkr.ecr.us-east-1.amazonaws.com"
    assignPath: "quay"
    pathTests:
      - subPath: "domain"
        condition: In
        value:
          - "quay.io"
