apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.team }}-limits
  namespace: {{ .Values.namespace }}
  labels:
    team: {{ .Values.team }}
    env:  {{ .Values.env }}
spec:
  limits:
    - type: Container
      default:
        cpu:    {{ .Values.limitRange.defaultCPULimit }}
        memory: {{ .Values.limitRange.defaultMemoryLimit }}
      defaultRequest:
        cpu:    {{ .Values.limitRange.defaultCPURequest }}
        memory: {{ .Values.limitRange.defaultMemoryRequest }}
      max:
        cpu:    {{ .Values.limitRange.maxCPU }}
        memory: {{ .Values.limitRange.maxMemory }}
