# cert-manager — staging (same footprint as dev)
installCRDs: true

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi

webhook:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi

cainjector:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi

serviceAccount:
  create: true
  name: cert-manager
  annotations: {}

prometheus:
  enabled: true
  servicemonitor:
    enabled: true

extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
