# Kong KIC — dev
replicaCount: 1

proxy:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

ingressController:
  enabled: true
  installCRDs: true  # installs Kong CRDs (KongPlugin, KongConsumer, etc.) — not Gateway API CRDs

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi
